[Distribution]
Distribution=fedora
Release=43
Architecture=arm64

[Output]
Format=disk
Output=fedora43
SectorSize=512
CompressOutput=no

[Content]
Bootable=yes
Autologin=yes
Hostname=comet
UnifiedKernelImages=no
Devicetree=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
PostInstallationScripts=mkosi.postinst

# include kernel and dracut so /boot has kernel + initramfs
Packages=
    NetworkManager
    accountsservice
    bash
    coreutils
    cryptsetup
    cuarzo-louvre
    cuarzo-louvre-examples
    curl
    dnf
    dracut
    dracut-network
    fedora-release
    greetd
    iproute
    kernel
    lvm2
    mechanix-notes
    mechanix-settings
    mesa-demos
    mesa-dri-drivers
    mesa-vulkan-drivers
    openssh-server
    passwd
    phoc
    plymouth
    sudo
    systemd
    systemd-boot-unsigned
    util-linux
    vim
    weston
    weston-demo
    wget
    xorg-x11-server-Xwayland

PackageDirectories=/opt/mecha
Packages=kernel-6.12.20+mecha+-4.aarch64
