[Distribution]
Distribution=fedora
Release=43
Architecture=arm64

[Output]
Format=disk
Output=fedora43
SectorSize=512
CompressOutput=no

[Content]
Bootable=yes
Autologin=yes
Hostname=comet
UnifiedKernelImages=no
Devicetree=freescale/imx8mp-mecha-comet.dtb
RootPassword=mecha
PostInstallationScripts=mkosi.postinst

# include kernel and dracut so /boot has kernel + initramfs
Packages=
    NetworkManager
    NetworkManager-wifi
    alacritty
    accountsservice
    bash
    bash-completion
    bluez
    coreutils
    cpufrequtils
    cryptsetup
    cuarzo-louvre
    cuarzo-louvre-examples
    curl
    dhclient
    dhcpcd
    dnf
    dracut
    dracut-network
    evtest
    fedora-release
    greetd
    gsettings-desktop-schemas
    htop
    i2c-tools
    iproute
    iw
    kernel
    kernel-tools
    libgpiod-utils
    lvm2
    mechanix-extension-service
    mechanix-files
    mechanix-keyboard
    mechanix-launcher
    mechanix-music
    mechanix-notes
    mechanix-settings
    mechanix-system-service
    mesa-demos
    mesa-dri-drivers
    mesa-vulkan-drivers
    mpv-devel
    mutter
    mxconf
    mxsearch
    nano
    ncurses
    net-tools
    openssh-server
    passwd
    phoc
    pipewire
    plymouth
    seatd
    session_service
    sudo
    systemd
    systemd-boot-unsigned
    usbutils
    util-linux
    vim
    weston
    weston-demo
    wget
    wpa_supplicant
    xorg-x11-server-Xwayland
    

PackageDirectories=rpms
Packages=
    kernel-6.12.20+mecha+-2.aarch64
    nxp-firmware-1.0-1.fc43.aarch64
